# -*- coding: utf-8 -*-
"""project103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XS8yuQdC3RhbflDUvEbKptHigW_-kU3C
"""

import pandas as pd
import plotly.express as px
df=pd.read_csv("data.csv")
fig=px.scatter(df,x='date',y='cases',color='country',title='Covid cases in China')
fig.show()